services:
  - type: web
    name: cartorio-anisio
    runtime: docker
    plan: starter
    autoDeployTrigger: commit
    healthCheckPath: /
    disk:
      name: cartorio-data
      mountPath: /var/www/html/storage
      sizeGB: 1
